package com.wafflestudio.bunnybunny.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_dark_primary = Color(0xFF222222)
val md_theme_dark_onPrimary = Color(0xFF454545)
val md_theme_dark_primaryContainer = Color(0xFF636363)
val md_theme_dark_onPrimaryContainer = Color(0xFFF0F0F0)
val md_theme_dark_secondary = Color(0xFFAAAAAA)
val md_theme_dark_onSecondary = Color(0xFF3E3E3E)
val md_theme_dark_secondaryContainer = Color(0xFF565656)
val md_theme_dark_onSecondaryContainer = Color(0xFFBDBDBD)
val md_theme_dark_tertiary = Color(0xFFB8B8B8)
val md_theme_dark_onTertiary = Color(0xFF242424)
val md_theme_dark_tertiaryContainer = Color(0xFF3A3A3A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4D4D4)
val md_theme_dark_error = Color(0xFFB4B4B4)
val md_theme_dark_errorContainer = Color(0xFF939393)
val md_theme_dark_onError = Color(0xFF696969)
val md_theme_dark_onErrorContainer = Color(0xFFDADADA)
val md_theme_dark_background = Color(0xFF1F1F1F)
val md_theme_dark_onBackground = Color(0xFFEAEAEA)
val md_theme_dark_surface = Color(0xFF1F1F1F)
val md_theme_dark_onSurface = Color(0xFFEAEAEA)
val md_theme_dark_surfaceVariant = Color(0xFF4F4F4F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3D3D3)
val md_theme_dark_outline = Color(0xFF9C9C9C)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1F1F)
val md_theme_dark_inverseSurface = Color(0xFFEAEAEA)
val md_theme_dark_inversePrimary = Color(0x82828282)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0x00000000)
val md_theme_dark_outlineVariant = Color(0xFF4F4F4F)
val md_theme_dark_scrim = Color(0xFF000000)

val md_theme_light_primary = Color(0xFFFFFFFF)
val md_theme_light_onPrimary = Color(0xFF000000)
val md_theme_light_primaryContainer = Color(0xFF111111)
val md_theme_light_onPrimaryContainer = Color(0xFFF0F0F0)
val md_theme_light_secondary = Color(0xFF555555)
val md_theme_light_onSecondary = Color(0xFFC1C1C1)
val md_theme_light_secondaryContainer = Color(0xFF9A9A9A)
val md_theme_light_onSecondaryContainer = Color(0xFF424242)
val md_theme_light_tertiary = Color(0xFF474747)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5C5C5)
val md_theme_light_onTertiaryContainer = Color(0xFF2B2B2B)
val md_theme_light_error = Color(0xFF4B4B4B)
val md_theme_light_errorContainer = Color(0xFF6C6C6C)
val md_theme_light_onError = Color(0xFF969696)
val md_theme_light_onErrorContainer = Color(0xFF252525)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1F1F1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1F1F1F)
val md_theme_light_surfaceVariant = Color(0xFFEEEEEE)
val md_theme_light_onSurfaceVariant = Color(0xFF2C2C2C)
val md_theme_light_outline = Color(0xFF636363)
val md_theme_light_inverseOnSurface = Color(0xFFE0E0E0)
val md_theme_light_inverseSurface = Color(0xFF1F1F1F)
val md_theme_light_inversePrimary = Color(0xFF7D7D7D)
val md_theme_light_shadow = Color(0xFFFFFFFF)
val md_theme_light_surfaceTint = Color(0x00000000)
val md_theme_light_outlineVariant = Color(0xFFFFFFFF)
val md_theme_light_scrim = Color(0xFFFFFFFF)



val seed = Color(0xFF555555)
