package com.wafflestudio.bunnybunny

import android.os.Build
import androidx.annotation.RequiresApi
import com.wafflestudio.bunnybunny.lib.network.dto.GoodsPostContent
import com.wafflestudio.bunnybunny.lib.network.dto.GoodsPostPreview
import java.sql.Timestamp
import java.time.LocalDateTime


object SampleData {

    val GoodsPostSample= listOf(
        GoodsPostPreview(
            id = 1,
            title="코멧5단정리함",
            repImg="https://dnvefa72aowie.cloudfront.net/origin/article/202401/5169264e8d830f83fc1547435761333f4ce68c47d2d4723fa2b185e1bd30fd3b_0.webp?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 2,
            chatCnt = 1,
            sellPrice = 3000,
            tradingLocation = "경기도 평택시 고덕동",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
        GoodsPostPreview(
            id = 2,
            title="Z플립4 기계값 15만원",
            repImg = "https://dnvefa72aowie.cloudfront.net/origin/article/202401/11f6a028b850d3ae41fcb740aeea8c25fc8325d14197c7496487a97602ca37d4.jpg?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 30,
            chatCnt = 7,
            sellPrice = 100000,
            tradingLocation = "경기도 파주시 금촌3동",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
        GoodsPostPreview(
            id = 3,
            title="국산 생강청+배도라지청 선물",
            repImg = "https://dnvefa72aowie.cloudfront.net/origin/article/202401/c20b04b8b5f6e63ae3306f74d063788b04b24b431713d3cf75206ba894992b50.jpg?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 0,
            chatCnt = 0,
            sellPrice = 8000,
            tradingLocation = "서울 노원구 상계1동",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
        GoodsPostPreview(
            id = 4,
            title="아이패드 6세대 팝니다",
            repImg = "https://dnvefa72aowie.cloudfront.net/origin/article/202312/2cf483dcf705e393cffe5435a703638b95d39fedd3203e09dd3910b78dd44b93_0.webp?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 0,
            chatCnt =3,
            sellPrice = 150000,
            tradingLocation = "광주 동구 동명동",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
        GoodsPostPreview(
            id = 5,
            title="철제선반",
            repImg = "https://dnvefa72aowie.cloudfront.net/origin/article/202312/490baf1fa26bac6941cac02715f4a3a3febd5d7b8ca8f023111fda36fc8bc846_0.webp?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 1,
            chatCnt =0,
            sellPrice = 10000,
            tradingLocation = "충남 아산시 배방읍",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
        GoodsPostPreview(
            id = 6,
            title="냉장고 판매합니다",
            repImg = "https://dnvefa72aowie.cloudfront.net/origin/article/202401/10d17fc0559904a67d9565d720c64e7c600c95a3f0ef0092677fccee11712c46_0.webp?q=82&s=300x300&t=crop&f=webp",
            createdAt = System.currentTimeMillis(),
            refreshedAt = System.currentTimeMillis(),
            wishCnt = 1,
            chatCnt =2,
            sellPrice = 54000,
            tradingLocation = "서울 노원구 상계3.4동",
            deadline = System.currentTimeMillis(),
            type = "TRADE",
            status = "NEW",
        ),
    )

    val GoodsPostContentSample=GoodsPostContent(
        id = 1,
        title="코멧5단정리함",
        description = "이건 아무튼 겁나 쩌는 코멧 5단 정리함입니다. 무려 정리가 가능합니다.",
        type = "TRADE",
        status = "NEW",
        authorId = 1,
        buyerId = -1,
        sellingArea = "경기도 평택시 고덕동",
        repImg="https://mblogthumb-phinf.pstatic.net/MjAyMTAyMDRfMjcz/MDAxNjEyNDA5MDEyMjg0.lIRX6wm7X3nPYaviwnUFyLm5dC88Mggadj_nglswSHsg.r9so4CS-g8VZGAoaRWrwmPCIuDOsgsU64fQu0kKQRTwg.JPEG.sunny_side_up12/1612312679152%EF%BC%8D11.jpg?type=w800",
        images= listOf("https://dnvefa72aowie.cloudfront.net/origin/article/202401/5169264e8d830f83fc1547435761333f4ce68c47d2d4723fa2b185e1bd30fd3b_0.webp?q=82&s=300x300&t=crop&f=webp","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTbZwffvLNKJyX9SWN9Mal4FtZyblWwSYnN2SsZknKHWTWpYACnfWz4Hms88Yyl4TKKkTTAIpj4HtYY385q0doAG6Ts6E_3IVWEVQqXPvILDCIcaKHlZSG2VnFYLk87K_Stqlzg0XY&usqp=CAc"),
        viewCnt=50,
        offerYn=true,
        refreshCnt = 3,
        refreshedAt = System.currentTimeMillis(),
        createdAt = System.currentTimeMillis(),
        deadline = System.currentTimeMillis(),
        hiddenYn = true,
        sellPrice = 3000,
        wishCnt = 2,
        chatCnt = 1,
    )

    val DefaultGoodsPostContentSample=GoodsPostContent(
        id = 0,
        title="",
        description = "",
        type = "TRADE",
        status = "NEW",
        authorId = 0,
        buyerId = -1,
        sellingArea = "",
        repImg="",
        images= listOf(),
        viewCnt=0,
        offerYn=true,
        refreshCnt = 0,
        refreshedAt = System.currentTimeMillis(),
        createdAt = System.currentTimeMillis(),
        deadline = System.currentTimeMillis(),
        hiddenYn = true,
        sellPrice = 0,
        wishCnt = 0,
        chatCnt = 0,
    )
}